name: Release Python package

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        # Use the PAT to authenticate the Git commands.
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # the python version your want to build and upload your package with
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: poetry install
    - name: Bump Version (use git tags)
      run: poetry version $(git describe --tags --abbrev=0)
    - name: Commit Changes
      run: |
        git config --global user.name "hansd99"
        git config --global user.email "hans.dekker99@gmail.com"
        git add pyproject.toml
        git commit -m "Bump version [skip ci]"
        git push origin HEAD:refs/heads/main
    - name: Install dependencies
      run: poetry install
    - name: Build package
      run: poetry build
    - name: Publish new distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
